Update sbt/g8 version
scala/scala-seed.g8 pull request #14
Opened 2017-08-22 11:49 UTC by amaya382

* sbt: 1.0.0
* giter8: 0.9.0

`g8 file://scala-seed.g8 --name=test` and then `sbt run` works fine with g8 0.9.0 and sbt 1.0.0

2017-08-22 11:54 UTC, xuwei-k requested changes

2017-08-22 11:54 UTC, xuwei-k commented on project/build.properties
> +sbt.version=1.0.0
g8 does not support sbt 1.0 https://github.com/foundweekends/giter8/issues/318

2017-09-30 03:24 UTC, seblm requested changes

2017-09-30 03:24 UTC, seblm commented on src/main/g8/project/build.properties
> +sbt.version=1.0.0
last sbt version is `1.0.2`

2018-01-17 21:06 UTC, SethTisue commented
I've just merged #19 which updates the sbt version.

@amaya382 I'm sorry, but this PR got lost in the shuffle. there is still a piece of this PR which #19 didn't cover, namely the sbt-giter8 version bump. if you rebase it, I'll merge it.

2018-01-22 04:36 UTC, amaya382 commented
@SethTisue I rebased and updated it to the latest version

2018-01-22 16:34 UTC, merged

2018-01-22 16:34 UTC, SethTisue commented
thank you!