Use scala-seed as the default
scala/scala-seed.g8 pull request #8
Opened 2017-04-27 20:47 UTC by wsargent

2017-04-27 20:57 UTC, eed3si9n requested changes

2017-04-27 20:57 UTC, eed3si9n commented on src/main/g8/default.properties
> +name=scala-seed
What's the motivation here?

I don't know if "My Something Project" is the best wording, would I think it's clear that you're suppose to replace it with the name of the project you're about to start.

2017-04-27 22:50 UTC, wsargent commented on src/main/g8/default.properties
> +name=scala-seed
Would 

```
name=Please enter name of the project you're about to start.
```

be better?

2017-04-28 00:39 UTC, eed3si9n commented on src/main/g8/default.properties
> +name=scala-seed
It currently renders like this:

```
 sbt new scala/scala-seed.g8
...
[info] Set current project to work (in build file:/xxx/work/)

Minimum Scala build.

name [My Something Project]:
```

I don't know if it should be too much longer than that. `Hello World Project`?

2017-04-30 18:59 UTC, wsargent commented on src/main/g8/default.properties
> +name=scala-seed
`Scala Seed Project`

2017-04-30 20:53 UTC, eed3si9n commented on src/main/g8/default.properties
> +name=scala-seed
ok. let's go with that.

2017-06-27 17:48 UTC, merged